<?php

namespace DeviceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DevicetypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevicetypesRepository extends EntityRepository
{
}
