DeviceBundle\Entity\Devicetypes:
    type: entity
    table: null
    repositoryClass: DeviceBundle\Repository\DevicetypesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        manufacturer:
            type: string
            length: 255
    lifecycleCallbacks: {  }
